# Generated by Django 2.1.9 on 2019-07-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20190704_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighCategoryTBL',
            fields=[
                ('highcategoryid', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='上位カテゴリID')),
                ('highcategoryname', models.CharField(max_length=15, verbose_name='上位カテゴリ名')),
            ],
            options={
                'db_table': 'highcategorytbl',
            },
        ),
        migrations.AlterField(
            model_name='categorytbl',
            name='highcategoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.HighCategoryTBL'),
        ),
    ]
