# Generated by Django 2.1.9 on 2019-07-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20190704_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytbl',
            name='categorydetails',
            field=models.CharField(default=1, max_length=30, verbose_name='カテゴリ詳細'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='categoryname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.CategoryTBL', verbose_name='カテゴリ名'),
        ),
    ]
