# Generated by Django 2.1.9 on 2019-07-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_auto_20190704_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstbl',
            old_name='categoryname',
            new_name='categoryid',
        ),
        migrations.RemoveField(
            model_name='categorytbl',
            name='categorydetails',
        ),
    ]
