# Generated by Django 2.1.9 on 2019-07-05 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0006_auto_20190704_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstbl',
            name='productno',
            field=models.CharField(default=1, max_length=9, verbose_name='製品番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorytbl',
            name='highcategoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.HighCategoryTBL', verbose_name='上位カテゴリID'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='categoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.CategoryTBL', verbose_name='カテゴリID'),
        ),
    ]
