# Generated by Django 2.1.9 on 2019-07-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_auto_20190705_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytbl',
            name='highcategoryid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searchapp.HighCategoryTBL', verbose_name='上位カテゴリID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.CategoryTBL', verbose_name='カテゴリID'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsdescription',
            field=models.CharField(max_length=150, null=True, verbose_name='商品記述'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsurl',
            field=models.URLField(max_length=100, null=True, verbose_name='商品画像URL'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='salesenddate',
            field=models.DateField(null=True, verbose_name='販売終了年月日'),
        ),
    ]
