# Generated by Django 2.1.9 on 2019-07-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0008_auto_20190705_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstbl',
            name='entrydate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登録年月日時分秒'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsdescription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='商品記述'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='goodsurl',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='商品画像URL'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='salesenddate',
            field=models.DateField(blank=True, null=True, verbose_name='販売終了年月日'),
        ),
        migrations.AlterField(
            model_name='goodstbl',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新年月日時分秒'),
        ),
    ]
