# Generated by Django 2.1.9 on 2019-07-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0009_auto_20190705_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytbl',
            options={'verbose_name_plural': 'カテゴリマスタ'},
        ),
        migrations.AlterModelOptions(
            name='goodstbl',
            options={'verbose_name_plural': '商品マスタ'},
        ),
        migrations.AlterModelOptions(
            name='highcategorytbl',
            options={'verbose_name_plural': '上位カテゴリマスタ'},
        ),
        migrations.AlterUniqueTogether(
            name='goodstbl',
            unique_together={('productno', 'sizename', 'colorname')},
        ),
    ]
