# Generated by Django 2.1.9 on 2019-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_auto_20190726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highcategorytbl',
            name='highcategoryid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='上位カテゴリID'),
        ),
    ]
