# Generated by Django 2.1.9 on 2019-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0011_auto_20190729_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytbl',
            name='categoryid',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='カテゴリID'),
        ),
        migrations.AlterField(
            model_name='highcategorytbl',
            name='highcategoryid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='上位カテゴリID'),
        ),
    ]
