# Generated by Django 2.1.9 on 2019-08-19 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0012_auto_20190729_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstbl',
            name='deleteflag',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='論理削除フラグ'),
        ),
    ]
