"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 2.1.9.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from .base import *


# 商用設定ファイルなのでFalseに変更
DEBUG = False  # 開発時はTrue,商用提供時はFalse

ALLOWED_HOSTS = ['*']  # デバックモードがFalseの時に設定要


# AWS用のデータベース定義
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'protodb',  # RDS構築時に設定したDB名
        'USER': 'testuser',  # RDS構築時に設定したユーザ名
        'PASSWORD': 'testpassword',  # ローカル端末にインストールしたときのパスワード
        # RDS作成時に生成されたエンドポイント名
        'HOST': 'rd-dev01.cfoy0i3ytiui.ap-northeast-1.rds.amazonaws.com',
        'PORT': '3306',
        # トランザクションの有効範囲をリクエストの開始から終了までに設定
        'ATOMIC_REQUESTS': True,
        'OPTIONS': {
            # 桁溢れの登録時にエラー（厳密モード）
            'sql_mode': 'TRADITIONAL,NO_AUTO_VALUE_ON_ZERO',
            },
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# デバックモードがFalseの時に有効化
STATIC_URL = '/static/'  # 静的ファイルの配信用ディレクトリ
# 個別のアプリではなく、トップページに表示する画像などを保管する場所を指定
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # 静的ファイルの置き場所
STATIC_ROOT = '/var/www/{}/static' .format(PROJECT_NAME)  # 静的ファイルの配信元

# セッションの設定
SESSION_COOKIE_AGE = 600  # 10分
SESSION_SAVE_EVERY_REQUEST = True  # 1リクエストごとにセッション情報更新
